# ==================================================
# RetailPulse ML - Online Retail Analysis
# ==================================================

# Load required packages
library(readxl)
install.packages("dplyr")
library(dplyr)
library(ggplot2)
install.packages("lubridate")
library(lubridate)

# Load raw dataset
retail_data <- read_excel("C:/Users/AR/Downloads/online+retail/Online Retail.xlsx")

# 1. Basic Data Inspection
# Why: Check the size and structure of the dataset before cleaning.
dim(retail_data)
str(retail_data)
summary(retail_data)

# Why: Identify missing values that may affect our analysis.
colSums(is.na(retail_data))

# Why: Check whether duplicate transaction records are present.
sum(duplicated(retail_data))

# Why: Understand unusual values before deciding how to clean the data.
summary(retail_data$Quantity)
summary(retail_data$UnitPrice)
table(substr(retail_data$InvoiceNo, 1, 1) == "C")

colSums(is.na(retail_data))
sum(duplicated(retail_data))
summary(retail_data$Quantity)
summary(retail_data$UnitPrice)

# 2. Data Cleaning
# Why: Remove records that cannot be used reliably for sales and customer analysis.

# Check cancelled invoices
sum(grepl("^C", retail_data$InvoiceNo))

# Check negative quantities
sum(retail_data$Quantity < 0)

# Check zero or negative prices
sum(retail_data$UnitPrice <= 0)

# Check missing customer IDs
sum(is.na(retail_data$CustomerID))
retail_clean <- retail_data %>%filter(!grepl("^C", InvoiceNo),Quantity > 0,UnitPrice > 0,!is.na(CustomerID))
# Why: Confirm how many valid transactions remain after cleaning.
dim(retail_clean)
# Check that the problematic values were removed
sum(retail_clean$Quantity <= 0)
sum(retail_clean$UnitPrice <= 0)
sum(is.na(retail_clean$CustomerID))
# Why: Calculate transaction revenue so we can analyze sales and customer spending.
retail_clean <- retail_clean %>%mutate(Revenue = Quantity * UnitPrice)
summary(retail_clean$Revenue)

# Sales Performance
# Why: Calculate the total revenue generated from valid transactions.
total_revenue <- sum(retail_clean$Revenue)
total_revenue

# Why: Count unique invoices to understand how many separate orders
# were made after cleaning the transaction data.
total_transactions <- n_distinct(retail_clean$InvoiceNo)
total_transactions

#------------------------- Interpretation------------------------------------
# The cleaned transactions generated approximately £8.91 million in total
# revenue across 18,532 unique orders. This gives us an overall view of
# the sales volume and revenue generated by the business during the period
# covered by the dataset.

# Why: Count unique customers to understand how many individual customers
# generated the orders in the cleaned dataset.
total_customers <- n_distinct(retail_clean$CustomerID)
total_customers

# ------------------------Interpretation----------------------------------------
# The cleaned dataset contains 4,338 unique customers. This shows that the
# 18,532 orders were generated by a smaller group of repeat and one-time
# customers, making customer-level analysis useful for understanding
# purchasing behavior.

# Why: Calculate the average revenue generated per order to understand
# the typical value of a customer transaction.
average_order_value <- total_revenue / total_transactions
average_order_value

# Interpretation:
# The average order value is approximately £480.87, meaning that each
# order generated about £481 in revenue on average during the period.

# Why: Examine monthly revenue to identify changes and patterns in sales
# over the period covered by the dataset.
monthly_revenue <- retail_clean %>%mutate(Month = floor_date(InvoiceDate, "month")) %>%group_by(Month) %>%summarise(Revenue = sum(Revenue),.groups = "drop")
monthly_revenue

# -----------------------Interpretation-------------------------------------
# Revenue varied across the year, with the highest monthly revenue in
# November 2011 at about £1.16 million. Sales increased strongly from
# September to November, while December recorded a noticeable drop.
# Overall, the results suggest higher sales toward the end of the year.

# Why: Visualize the monthly revenue trend to make changes in sales
# over time easier to identify.
ggplot(monthly_revenue, aes(x = Month, y = Revenue)) +geom_line() +geom_point() +labs(title = "Monthly Revenue Trend",x = "Month",y = "Revenue (£)") +theme_minimal()

#-------------------- Interpretation----------------------------------------
# The plot shows that monthly revenue fluctuated during the first half
# of the year. Revenue increased sharply from September and reached its
# highest level in November 2011. It then dropped noticeably in December,
# showing a strong change in sales toward the end of the year.

# Revenue by Country
# Why: Compare revenue across countries to identify the main markets
# contributing to the business.
country_revenue <- retail_clean %>%group_by(Country) %>%summarise(Revenue = sum(Revenue),.groups = "drop") %>%arrange(desc(Revenue))
country_revenue

# Why: Visualize the top 10 countries by revenue to compare the main
# markets more clearly.
top_10_countries <- country_revenue %>%slice_head(n = 10)
ggplot(top_10_countries, aes(x = reorder(Country, Revenue), y = Revenue)) +geom_col() +coord_flip() +labs(title = "Top 10 Countries by Revenue",x = "Country",y = "Revenue (£)") +theme_minimal()

#--------------------------- Interpretation---------------------------------
# The United Kingdom generates by far the highest revenue, much more than
# the other countries in the top 10. The Netherlands, EIRE, Germany, and
# France are the next largest markets, but their revenue is considerably
# lower. Overall, the business is highly concentrated in the UK market.

# Why: Count the number of unique orders made by each customer to understand
# customer purchase frequency.
customer_orders <- retail_clean %>%group_by(CustomerID) %>%summarise(Orders = n_distinct(InvoiceNo),.groups = "drop")
summary(customer_orders$Orders)

#------------------------------ Interpretation--------------------------------
# Customers made between 1 and 209 orders. The median customer placed
# 2 orders, while the average was about 4.27 orders. This difference
# suggests that some customers made many more purchases than most customers.

# Why: Visualize the distribution of customer order frequency and identify
# whether a small number of customers make many more orders than others.
ggplot(customer_orders, aes(x = Orders)) +geom_histogram(binwidth = 1) +labs(title = "Distribution of Customer Order Frequency",x = "Number of Orders",y = "Number of Customers") +theme_minimal()

# ----------------------------Interpretation-----------------------------------
# The histogram shows a strongly right-skewed distribution. Most customers
# made only a small number of orders, while a small number of customers
# placed many more orders. This suggests that repeat purchasing is
# concentrated among a relatively small group of customers.

# Customer Revenue
# Why: Calculate the total revenue generated by each customer to understand
# differences in customer value.
customer_revenue <- retail_clean %>%group_by(CustomerID) %>%summarise(Revenue = sum(Revenue),.groups = "drop")
summary(customer_revenue$Revenue)

#------------------------------ Interpretation---------------------------------
# Customer revenue varies considerably. The median customer generated about
# £674 in revenue, while the average was higher at about £2,054. The maximum
# customer revenue was approximately £280,206, showing that a small number
# of customers generated much higher revenue than most customers.

# Why: Visualize the distribution of customer revenue and identify whether
# revenue is concentrated among a small number of high-value customers.
ggplot(customer_revenue, aes(x = Revenue)) +geom_histogram(bins = 50) +labs(title = "Distribution of Customer Revenue",x = "Customer Revenue (£)",y = "Number of Customers") +theme_minimal()

#--------------------------- Interpretation--------------------------------
# The plot shows that most customers generated relatively low revenue,
# while only a small number of customers generated very high revenue.
# The long right tail confirms that customer value is concentrated among
# a smaller group of high-revenue customers.

# Top Customers by Revenue
# Why: Identify the highest-revenue customers to understand which customers
# contribute most to overall sales.
top_customers <- customer_revenue %>%arrange(desc(Revenue)) %>%slice_head(n = 10)
top_customers

#------------------------- Interpretation------------------------------------
# Customer 14646 generated the highest revenue at about £280,206,
# followed by customers 18102 and 17450. The top customers generated
# substantially more revenue than most customers, showing that a small
# group contributes a large amount of sales.

# Why: Visualize the highest-revenue customers to compare their contribution
# to sales more clearly.
ggplot(top_customers, aes(x = reorder(factor(CustomerID), Revenue), y = Revenue)) +geom_col() +coord_flip() +labs(title = "Top 10 Customers by Revenue",x = "Customer ID",y = "Revenue (£)") +theme_minimal()

# ----------------------------Interpretation------------------------------------
# The plot shows that customer revenue varies substantially among the top
# customers. Customer 14646 generated the highest revenue, followed by
# customers 18102 and 17450. The difference between these customers and
# the lower-ranked customers shows that sales are concentrated among a
# relatively small group of high-value customers.

# RFM(Recency Frequency Monetary) Analysis
# Why: Measure how recently each customer made a purchase, which helps
# identify customers who are currently more active.
analysis_date <- max(retail_clean$InvoiceDate) + days(1)
customer_recency <- retail_clean %>%group_by(CustomerID) %>%summarise(Recency = as.numeric(difftime(analysis_date,max(InvoiceDate),units = "days")),.groups = "drop")
summary(customer_recency$Recency)

#-------------------------- Interpretation---------------------------------
# Customer recency ranges from 1 to about 374 days. The median customer
# made their most recent purchase about 51 days before the analysis date,
# while the average was about 93 days. This indicates that some customers
# purchased recently, while others had not purchased for several months.

# Why: Measure how frequently each customer placed orders, which helps
# distinguish one-time customers from repeat customers.
customer_frequency <- retail_clean %>%group_by(CustomerID) %>%summarise(Frequency = n_distinct(InvoiceNo),.groups = "drop")
summary(customer_frequency$Frequency)

# ----------------------Interpretation---------------------------------------
# Customers placed between 1 and 209 orders. The median customer placed
# 2 orders, while the average was about 4.27 orders. The higher maximum
# shows that a small number of customers placed many more orders than most.

# Why: Measure how much each customer spent in total, which helps identify
# customers with higher monetary value.
customer_monetary <- retail_clean %>%group_by(CustomerID) %>%summarise(Monetary = sum(Revenue),.groups = "drop")
summary(customer_monetary$Monetary)

#-------------------------------- Interpretation-------------------------------
# Customer spending varies considerably. The median customer spent about
# £674, while the average was about £2,054. The maximum spending of about
# £280,206 shows that a small number of customers contributed much more
# revenue than most customers.

# Combine RFM Metrics
# Why: Combine the three RFM measures into one dataset so each customer
# has a complete profile for segmentation.
rfm_data <- customer_recency %>%left_join(customer_frequency, by = "CustomerID") %>%left_join(customer_monetary, by = "CustomerID")
head(rfm_data)

#-------------------------- Interpretation-----------------------------------
# The RFM dataset gives each customer a complete profile based on their
# recent activity, number of orders, and total spending. For example,
# customer 12347 purchased recently and placed 7 orders, while customer
# 12346 has not purchased for a long time but has generated high revenue.
# These differences will help us identify different customer segments.

# RFM Distribution
# Why: Examine the distributions of Recency, Frequency, and Monetary
# values before applying customer segmentation.
summary(rfm_data[, c("Recency", "Frequency", "Monetary")])

#---------------------------- Interpretation---------------------------------
# The RFM variables show substantial variation between customers. Recency
# ranges from about 1 to 374 days, while Frequency ranges from 1 to 209
# orders. Monetary value is also highly variable, ranging from about £4
# to £280,206. These differences should be considered before clustering.

# Standardize RFM Variables
# Why: Standardize the RFM variables so that variables with larger numeric
# scales, such as Monetary, do not dominate the clustering process.
rfm_scaled <- scale(rfm_data[, c("Recency", "Frequency", "Monetary")])
head(rfm_scaled)

# --------------------------Interpretation------------------------------------
# The RFM variables have been standardized to comparable scales.
# Most values are relatively close to 0, while larger positive or negative
# values show customers who are quite different from the average.
# This prepares the RFM data for clustering without allowing Monetary
# to dominate because of its larger numeric scale.

# Choosing the Number of Clusters
# Why: Find a suitable number of customer groups before running K-Means.
wss <- sapply(1:10, function(k) {kmeans(rfm_scaled, centers = k, nstart = 25)$tot.withinss})
elbow_data <- data.frame(Clusters = 1:10,WSS = wss)
ggplot(elbow_data, aes(x = Clusters, y = WSS)) +geom_line() +geom_point()+ labs(title = "Elbow Method for Choosing Number of Clusters",x = "Number of Clusters",y = "Within-Cluster Sum of Squares") + theme_minimal()

#------------------------- Interpretation-------------------------------------
# The WSS decreases sharply as the number of clusters increases from 1 to 3.
# After 3 clusters, the improvement becomes more gradual. Based on the elbow
# plot, 3 clusters appears to be a reasonable choice for grouping customers.

# K-Means Customer Segmentation
# Why: Group customers with similar purchasing behavior based on their
# Recency, Frequency, and Monetary values.
set.seed(123)
kmeans_model <- kmeans(rfm_scaled,centers = 3,nstart = 25)
# Add cluster labels to the customer data
rfm_data$Cluster <- kmeans_model$cluster
# Check number of customers in each cluster
table(rfm_data$Cluster)

#--------------------------- Interpretation---------------------------------
# The K-Means model divided the customers into three groups.
# Cluster 2 is the largest group with 3,225 customers, followed by
# Cluster 1 with 1,087 customers. Cluster 3 contains only 26 customers,
# suggesting that these customers have very different purchasing behavior
# compared with the larger customer groups.

# RFM Profile by Customer Cluster
# Why: Compare Recency, Frequency, and Monetary values to understand
# the purchasing behavior of each customer segment.
cluster_summary <- rfm_data %>%group_by(Cluster) %>%summarise(Customers = n(),Avg_Recency = mean(Recency),Avg_Frequency = mean(Frequency),Avg_Monetary = mean(Monetary),.groups = "drop")
cluster_summary

# Interpretation:
# Cluster 1 contains 1,087 customers who have not purchased recently,
# with an average recency of about 247 days. They also have relatively
# low purchase frequency and spending.
#
# Cluster 2 is the largest group with 3,225 customers. These customers
# purchased more recently, averaging about 42 days, with around 4.68 orders
# and £1,858 in average spending.
#
# Cluster 3 contains only 26 customers, but they are very different from
# the other groups. They purchased very recently, placed about 66 orders
# on average, and generated approximately £85,904 in average spending.
# This represents a small group of extremely high-value customers.

# Customer Segment Comparison
# Why: Visualize the difference in customer value across the three segments.
ggplot(cluster_summary, aes(x = factor(Cluster),y = Avg_Monetary)) +geom_col() +labs(title = "Average Customer Revenue by Cluster",x = "Customer Cluster",y = "Average Revenue (£)") +theme_minimal()

# Interpretation:
# Cluster 3 has a much higher average revenue than the other two clusters,
# showing that this small group contains extremely high-value customers.
# Cluster 2 has higher average revenue than Cluster 1, while Cluster 1
# represents customers with relatively low spending.

# RFM Comparison Across Customer Clusters
# Why: Compare all three RFM measures to get a complete picture of
# how customer behavior differs between the segments.
install.packages("tidyr")
library(tidyr)
rfm_long <- rfm_data %>%group_by(Cluster) %>%summarise(Recency = mean(Recency),Frequency = mean(Frequency),Monetary = mean(Monetary),.groups = "drop") %>%tidyr::pivot_longer(cols = c(Recency, Frequency, Monetary),names_to = "Metric",values_to = "Average")
ggplot(rfm_long, aes(x = factor(Cluster), y = Average)) +geom_col() +facet_wrap(~Metric, scales = "free_y") +labs(title = "RFM Comparison Across Customer Clusters",x = "Customer Cluster",y = "Average Value") +theme_minimal()

-----------------------------# Interpretation--------------------------------
# Cluster 1 has the highest recency, meaning these customers have not
# purchased for a long time. They also have low frequency and spending.
#
# Cluster 2 has much lower recency and higher frequency and spending,
# showing a group of regular and relatively active customers.
#
# Cluster 3 has very low recency, very high frequency, and extremely
# high monetary value. Although this group is small, these customers
# are highly active and generate much more revenue than the other groups.

# Cluster Quality Evaluation
# Why: Measure how well each customer fits within its assigned cluster
# compared with the other clusters.
install.packages("cluster")
library(cluster)
silhouette_scores <- silhouette(kmeans_model$cluster,dist(rfm_scaled))
summary(silhouette_scores)

# Interpretation:
# The overall average silhouette width is about 0.59, which indicates
# reasonably well-separated clusters overall.
#
# Clusters 1 and 2 have good average silhouette values of about 0.59 and
# 0.60, showing that most customers in these groups fit their assigned
# clusters reasonably well.
#
# Cluster 3 has a much lower silhouette value of about 0.07. This means
# the 26 high-value customers are not as clearly separated from the other
# groups based on the standardized RFM variables.

# Comparing Different Numbers of Clusters
# Why: Check whether another number of clusters provides better-separated
# customer segments than the 3-cluster solution.
silhouette_results <- data.frame(Clusters = 2:6,Silhouette = sapply(2:6, function(k) {model <- kmeans(rfm_scaled,centers = k,nstart = 25)sil <- silhouette(model$cluster,dist(rfm_scaled))mean(sil[, "sil_width"])}))
silhouette_results

# ------------------------Interpretation-------------------------------------
# The 2-cluster solution has the highest average silhouette score at about
# 0.90, indicating very clear separation between the two customer groups.
# The 3-cluster solution has a lower score of about 0.59, while the scores
# for 4 to 6 clusters are also lower. Based on cluster separation, 2
# clusters provides the clearest segmentation of the customers.

# Final K-Means Clustering
# Why: Create the final customer segments using the number of clusters
# that gave the strongest silhouette result.
set.seed(123)
final_kmeans <- kmeans(rfm_scaled,centers = 2,nstart = 25)
rfm_data$Final_Cluster <- final_kmeans$cluster
# Check the number of customers in each cluster
table(rfm_data$Final_Cluster)

# Final Customer Segment Profiles
# Why: Compare the RFM characteristics of the two final clusters
# so we can understand what each customer segment represents.
final_cluster_summary <- rfm_data %>%group_by(Final_Cluster) %>%summarise(Customers = n(),Avg_Recency = mean(Recency),Avg_Frequency = mean(Frequency),Avg_Monetary = mean(Monetary),.groups = "drop")
final_cluster_summary

# Interpretation:
# Cluster 1 contains 4,312 customers and represents the main customer group.
# These customers have an average recency of about 94 days, around 4 orders,
# and average spending of about £1,549.
#
# Cluster 2 contains only 26 customers, but they are extremely different.
# They purchased much more recently, with an average of about 66 orders
# and average spending of approximately £85,904.
#
# Overall, the clustering identifies a large group of regular customers
# and a very small group of extremely high-value customers.

# Final Customer Segment Sizes
# Why: Visualize the size of each final customer segment.
ggplot(final_cluster_summary,aes(x = factor(Final_Cluster), y = Customers)) +geom_col() +labs(title = "Customer Segment Sizes",x = "Customer Segment",y = "Number of Customers") +theme_minimal()

#---------------------------- Interpretation-----------------------------------
# The plot shows that Cluster 1 contains the vast majority of customers,
# while Cluster 2 contains only a very small number of customers.
# Specifically, Cluster 1 has 4,312 customers and Cluster 2 has only 26.
# This shows that the high-value customer segment is very small compared
# with the main customer group.

# 10. Define Prediction Period
# Why: Set a cutoff date so we can use past customer behavior
# to predict whether they purchase in the following period.
cutoff_date <- as.POSIXct("2011-11-01")
cutoff_date

# Create Historical Customer Data
# Why: Use only past transactions to create the information
# that the ML model will use for prediction.
historical_data <- retail_clean %>%filter(InvoiceDate < cutoff_date)
dim(historical_data)

#---------------------------- Interpretation-------------------------------
# We now have 316,049 transaction records from before November 1, 2011.
# These records represent the past customer behavior that we will use
# to build our ML prediction features.

#  Create Historical Customer Features
# Why: Summarize each customer's past purchasing behavior
# so the ML model can learn from their previous activity.
customer_features <- historical_data %>%group_by(CustomerID) %>%summarise(Recency = as.numeric(difftime(cutoff_date,max(InvoiceDate),units = "days")),Frequency = n_distinct(InvoiceNo),Monetary = sum(Revenue),.groups = "drop")
head(customer_features)

#----------------------------- Interpretation-----------------------------------
# The table summarizes each customer's past behavior before November 1, 2011.
# For example, customer 12347 purchased recently, made 6 orders, and spent
# about £4,085. These past behaviors will be used as inputs for our ML model.

# Create Future Purchase Target
# Why: Create the answer that our ML model will learn to predict:
# whether a customer makes a purchase in the 30 days after the cutoff date.
future_data <- retail_clean %>%filter(InvoiceDate >= cutoff_date,InvoiceDate < cutoff_date + days(30))
future_customers <- future_data %>%distinct(CustomerID) %>%mutate(Purchased_Next_30_Days = 1)
customer_features <- customer_features %>%left_join(future_customers,by = "CustomerID") %>%mutate(Purchased_Next_30_Days = ifelse(is.na(Purchased_Next_30_Days),0,Purchased_Next_30_Days))
table(customer_features$Purchased_Next_30_Days)

# ---------------------------Interpretation------------------------------------------
# Out of 3,974 customers, 1,341 made at least one purchase during the
# 30 days after November 1, 2011, while 2,633 customers did not purchase.
# This gives us a binary target with two groups: purchased and did not purchase.

# Check Target Proportions
# Why: Check whether the two target groups are reasonably balanced
# before training the ML model.
prop.table(table(customer_features$Purchased_Next_30_Days))

# Interpretation:
# About 66.3% of customers did not purchase in the next 30 days,
# while about 33.7% did purchase. The two groups are not perfectly equal,
# but the difference is reasonable, so we do not have a severe class
# imbalance problem.

# Split Data into Training and Testing Sets
# Why: Keep some customers separate so we can test how well
# the ML model predicts customers it has not seen before.
set.seed(123)
train_index <- sample(1:nrow(customer_features),size = 0.8 * nrow(customer_features))
train_data <- customer_features[train_index, ]
test_data <- customer_features[-train_index, ]
dim(train_data)
dim(test_data)
dim(test_data)

# First ML Model - Logistic Regression
# Why: Use logistic regression to learn how past customer behavior
# can predict whether a customer will purchase in the next 30 days.
ml_model <- glm(Purchased_Next_30_Days ~ Recency + Frequency + Monetary,data = train_data,family = binomial)
summary(ml_model)

#---------------------------- Interpretation-------------------------------
# The model shows that Recency and Frequency are important predictors of
# future purchasing. Customers who purchased more recently and made more
# previous orders are more likely to purchase again. Monetary is not
# statistically significant in this model, suggesting that past spending
# alone is not a strong predictor of purchasing in the next 30 days.

# Predict Future Purchases
# Why: Use the trained ML model to estimate the probability
# that each new customer will purchase in the next 30 days.
test_data$Purchase_Probability <- predict(ml_model,newdata = test_data,type = "response")
head(test_data[, c("CustomerID","Recency","Frequency","Monetary","Purchase_Probability")])

#---------------------------- Interpretation----------------------------------------
# The model gives each customer a probability of making a purchase in the
# next 30 days. Customers with more recent and frequent purchases generally
# receive higher predicted probabilities.

# Convert Probabilities into Predictions
# Why: Convert the predicted probabilities into Yes/No decisions
# so we can compare the model's predictions with the actual outcomes.
test_data$Predicted_Purchase <- ifelse(test_data$Purchase_Probability >= 0.5,1,0)
table(test_data$Predicted_Purchase)

#-------------------------- Interpretation-----------------------------------
# Using a 0.5 probability threshold, the model predicts that 112 customers
# will purchase in the next 30 days, while 683 customers will not purchase.
# We now need to compare these predictions with what actually happened.

# Confusion Matrix
# Why: Compare the model's predictions with the actual customer outcomes
# to see how well the ML model performed on unseen customers.
table(Actual = test_data$Purchased_Next_30_Days,Predicted = test_data$Predicted_Purchase)

#----------------------------- Interpretation------------------------------
# The model correctly predicted 497 customers who did not purchase and
# 84 customers who did purchase. However, it missed 186 customers who
# actually purchased. This means the model is better at identifying
# customers who will not purchase than customers who will purchase.

# Model Accuracy
# Why: Measure the overall percentage of predictions that were correct.
accuracy <- mean(test_data$Predicted_Purchase == test_data$Purchased_Next_30_Days)
accuracy

#------------------------------ Interpretation-----------------------------
# The model correctly classified about 73.1% of the customers in the
# test dataset. This gives a reasonable overall result, but accuracy
# alone does not tell us how well the model identifies customers who
# actually purchase.

# Sensitivity (Recall)
# Why: Measure how well the model identifies customers who actually
# make a purchase in the next 30 days.
true_positive <- sum(test_data$Purchased_Next_30_Days == 1 &test_data$Predicted_Purchase == 1)
actual_positive <- sum(test_data$Purchased_Next_30_Days == 1)
sensitivity <- true_positive / actual_positive
sensitivity

#---------------------------- Interpretation----------------------------------
# The model correctly identified about 31.1% of the customers who actually
# purchased in the next 30 days. This means the model missed many potential
# purchasers, so its ability to identify future buyers is currently limited.

# Specificity
# Why: Measure how well the model identifies customers who do not
# make a purchase in the next 30 days.
true_negative <- sum(test_data$Purchased_Next_30_Days == 0 &test_data$Predicted_Purchase == 0)
actual_negative <- sum(test_data$Purchased_Next_30_Days == 0)
specificity <- true_negative / actual_negative
specificity

#---------------------------- Interpretation-----------------
# The model correctly identified about 94.7% of the customers who did not
# purchase in the next 30 days. This shows that the model is much better at
# identifying non-purchasers than identifying future purchasers.

# Precision
# Why: Measure how often the customers predicted to purchase
# actually make a purchase.
true_positive <- sum(test_data$Purchased_Next_30_Days == 1 &test_data$Predicted_Purchase == 1)
predicted_positive <- sum(test_data$Predicted_Purchase == 1)
precision <- true_positive / predicted_positive
precision

#--------------------------- Interpretation---------------------------------
# When the model predicts that a customer will purchase, it is correct
# about 75% of the time. This is a good result, although the model still
# misses many customers who actually purchase.

# F1 Score
# Why: Combine precision and sensitivity into one measure
# to evaluate how well the model identifies future purchasers.
f1_score <- 2 * (precision * sensitivity) / (precision + sensitivity)
f1_score

# -----------------------------Interpretation-------------------------------
# The F1 score is about 0.44, showing that the model has a reasonable
# balance between precision and sensitivity, but its ability to identify
# future purchasers still needs improvement.

# ROC Curve and AUC
# Why: Evaluate how well the model separates customers who purchase
# from customers who do not across different probability thresholds.
install.packages("pROC")
library(pROC)
roc_model <- roc(test_data$Purchased_Next_30_Days,test_data$Purchase_Probability)
auc_value <- auc(roc_model)
auc_value

# -------------------------------Interpretation--------------------------------
# The model has an AUC of about 0.72, showing that it has a moderate ability
# to distinguish between customers who will purchase and those who will not.
# This suggests the model has useful predictive information, although there
# is still room for improvement.

# ROC Curve
# Why: Visualize how the model's ability to identify purchasers changes
# when we use different probability thresholds.
plot(roc_model,main = "ROC Curve - Logistic Regression")

#---------------------------Interpretation-----------------------------------
# The ROC curve stays above the diagonal reference line, showing that
# the logistic regression model performs better than random guessing.
# The AUC of 0.72 indicates moderate ability to distinguish between
# customers who will purchase and those who will not.

# 27. Random Forest Model
# --------------------------------------------------

# Why: Train another machine learning model so we can compare
# its predictions with the logistic regression model.
install.packages("randomForest")
library(randomForest)
set.seed(123)
rf_model <- randomForest(factor(Purchased_Next_30_Days) ~ Recency + Frequency + Monetary,data = train_data,ntree = 500)
rf_model

#------------------------------ Interpretation-------------------------------------
# The Random Forest has an OOB error rate of about 27.1%, meaning that
# roughly 73% of training observations were classified correctly during
# the model's internal validation. The model identifies non-purchasers
# much better than purchasers, as it correctly identifies 1,930 customers
# in class 0 but misses many customers in class 1.

#Random Forest Test Predictions
# Why: Test the Random Forest on customers that were not used to train
# the model so we can fairly evaluate its predictive performance.
rf_probability <- predict(rf_model,newdata = test_data,type = "prob")[, "1"]
rf_prediction <- ifelse(rf_probability >= 0.5,1,0)
table(Actual = test_data$Purchased_Next_30_Days,Predicted = rf_prediction)

#---------------------------- Interpretation---------------------------------
# Random Forest correctly identified 490 non-purchasers and 91 purchasers.
# It identified slightly more purchasers than logistic regression, but
# still missed 179 customers who actually purchased.

# Random Forest Model Evaluation
# Why: Calculate several performance measures together so we can
# fairly compare the Random Forest with the logistic regression model.
rf_actual <- test_data$Purchased_Next_30_Days
rf_TP <- sum(rf_actual == 1 & rf_prediction == 1)
rf_TN <- sum(rf_actual == 0 & rf_prediction == 0)
rf_FP <- sum(rf_actual == 0 & rf_prediction == 1)
rf_FN <- sum(rf_actual == 1 & rf_prediction == 0)
rf_accuracy <- (rf_TP + rf_TN) / length(rf_actual)
rf_sensitivity <- rf_TP / (rf_TP + rf_FN)
rf_specificity <- rf_TN / (rf_TN + rf_FP)
rf_precision <- rf_TP / (rf_TP + rf_FP)
rf_f1 <- 2 * (rf_precision * rf_sensitivity) / (rf_precision + rf_sensitivity)
rf_metrics <- data.frame(Accuracy = rf_accuracy,Sensitivity = rf_sensitivity,Specificity = rf_specificity,Precision = rf_precision,F1_Score = rf_f1)
rf_metrics

#----------------------------- Interpretation-------------------------------------
# The Random Forest correctly classifies about 73.1% of the test customers.
# It identifies about 33.7% of actual purchasers and about 93.3% of
# non-purchasers. When it predicts a purchase, it is correct about 72.2%
# of the time. The F1 score of 0.46 shows a small improvement in identifying
# future purchasers compared with the logistic regression model.

# Compare ML Models
# Why: Compare the performance of both models using the same evaluation
# metrics to determine which model performs better.
model_comparison <- data.frame(Model = c("Logistic Regression","Random Forest"),Accuracy = c(accuracy,rf_accuracy),Sensitivity = c(sensitivity,rf_sensitivity),Specificity = c(specificity,rf_specificity),Precision = c(precision,rf_precision),F1_Score = c(f1_score,rf_f1))
model_comparison

#------------------------------- Interpretation---------------------------------
# Both models have the same overall accuracy of about 73.1%.
# Random Forest performs slightly better at identifying actual purchasers,
# with higher sensitivity and F1 score. Logistic Regression has better
# specificity and precision, meaning it is better at identifying
# non-purchasers and is more accurate when it predicts a purchase.
# Overall, Random Forest is slightly better for identifying future
# purchasers, while the difference between the two models is small.

# Random Forest ROC Curve and AUC
# Why: Measure how well the Random Forest separates customers who
# purchase from those who do not across different probability thresholds.
rf_roc <- roc(test_data$Purchased_Next_30_Days,rf_probability)
rf_auc <- auc(rf_roc)
rf_auc

#---------------------------------- Interpretation-----------------------------------
# The Random Forest has an AUC of about 0.71, showing a moderate ability
# to distinguish between customers who will purchase and those who will not.
# Its AUC is slightly lower than the Logistic Regression AUC of 0.72,
# so Logistic Regression performs slightly better when considering
# discrimination across all probability thresholds.

# Final Customer Predictions
# Why: Rank customers by their predicted purchase probability
# so the business can identify customers who are more likely to purchase.
final_predictions <- test_data %>%select(CustomerID,Recency,Frequency,Monetary,Purchase_Probability) %>%arrange(desc(Purchase_Probability))
head(final_predictions, 10)

# -----------------------------Interpretation-----------------------------------
# The model assigns very high purchase probabilities to customers who have
# purchased recently and frequently. For example, the top customers have
# probabilities close to 1, suggesting that they are strong candidates
# for future purchase activity.

# Customer Purchase Probability Categories
# Why: Convert model probabilities into simple categories
# so customers can be grouped by their likelihood of purchasing.
final_predictions <- final_predictions %>%mutate(Purchase_Category = case_when(Purchase_Probability >= 0.70 ~ "High",Purchase_Probability >= 0.30 ~ "Medium",TRUE ~ "Low"))
table(final_predictions$Purchase_Category)

#-----------------------Interpretation---------------------------------
# The model classified 51 customers as having a high probability of
# purchasing, 276 as having a medium probability, and 468 as having
# a low probability. This gives the business a simple way to prioritize
# customers for future marketing activities.

# Customer Purchase Probability Categories Plot
# Why: Visualize the number of customers in each prediction category
# so the distribution of predicted purchase likelihood is easy to compare.
ggplot(final_predictions,aes(x = Purchase_Category)) +geom_bar() +labs(title = "Customer Purchase Probability Categories",x = "Purchase Probability Category",y = "Number of Customers") +theme_minimal()

#--------------------------- Interpretation----------------------------------------
# The plot shows that most customers are classified as having a low
# probability of purchasing in the next 30 days. There are 468 low-probability
# customers, 276 medium-probability customers, and only 51 high-probability
# customers. This suggests that the business should focus its marketing
# efforts mainly on the smaller group of customers with higher purchase
# probabilities.

#---------------------------------------------------
# 35. Project Conclusion
# --------------------------------------------------

# Why: Summarize the main findings from the retail analysis,
# customer segmentation, and machine learning models.

# Conclusion:
# The analysis of the Online Retail dataset showed that the business
# generated approximately £8.91 million in revenue from 18,532 orders
# and 4,338 customers. Sales were highly concentrated in the UK, while
# a small number of customers contributed a large amount of revenue.
#
# RFM analysis and K-Means clustering identified two main customer groups.
# Most customers belonged to the regular customer segment, while a very
# small group represented extremely high-value customers.
#
# For machine learning, Logistic Regression and Random Forest were used
# to predict whether customers would make a purchase in the next 30 days.
# Logistic Regression achieved an AUC of about 0.72 and was selected as
# the final model because it had slightly better overall discrimination,
# specificity, and precision.
#
# The final predictions showed that most customers had a low predicted
# probability of purchasing, while a smaller group had medium or high
# purchase probabilities. These predictions can help the business focus
# marketing efforts on customers who are more likely to purchase.